<?php
$cfg = array( 
'shopnm' => '고톡', 
'shopurl' => 'http://massage0408.cafe24.com', 
'shopadm' => '', 
'shopemail' => '', 
'comnm' => '고톡', 
'comceo' => '', 
'comserial' => '', 
'comsaleno' => '', 
'comtel' => '', 
'comfax' => '', 
'comzip' => '', 
'comadr' => '', 
'shoptit' => '고톡', 
'shopkeyword' => '', 
'shopinfo' => '1', 
'unid' => 'admin,administration,administrator,master,webmaster,manage,manager,hyowoo
', 
'mpoint' => '1000', 
'bbank' => 'Y', 
'transM' => '2500', 
'ntransM' => '10000', 
'imgMX' => '190', 
'imgMY' => '150', 
'imgSX' => '190', 
'imgSY' => '150', 
'imgMMX' => '249', 
'imgMMY' => '192', 
'eshoptit' => '', 
'cshoptit' => '', 
'imgBX' => '435', 
'imgBY' => '308', 
'imgHX' => '222', 
'imgHY' => '111', 
'bsms' => 'Y', 
'sms' => 'n-forum', 
'sms_id' => 'sinbiweb', 
'sms_pw' => 'bong5584', 
'caller' => '02-1544-0835', 
'receive' => '010-1111-2222', 
'site_path' => '/home1/yunoshop/www/kcp'
 ); 
?>